language: node_js
node_js: 
  - 12.8.0
go:
  - 1.12.7
sudo: required
services: docker
cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli
#  - export GOPATH=$TRAVIS_BUILD_DIR/go
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save
  - cd $TRAVIS_BUILD_DIR/go/src/server
  - dep ensure
  - cd $TRAVIS_BUILD_DIR
  - hexo clean
# 执行清缓存，生成网页操作
script:
  - hexo generate
  - cd $TRAVIS_BUILD_DIR/go/src/server
  - go build
  - mv server $TRAVIS_BUILD_DIR/public/
  - cd $TRAVIS_BUILD_DIR
  - docker build --rm -t qq960826/blog .
# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - cd $TRAVIS_BUILD_DIR
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push qq960826/blog

# End: Build LifeCycle